# Generated by Django 5.0.6 on 2024-06-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_category_description_remove_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
