# Generated by Django 5.0.6 on 2024-06-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_ingredients_alter_recipe_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rate',
            field=models.IntegerField(default=3),
        ),
    ]
